name: Auto Tag
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check bump
        id: vbump
        uses: rgryta/Check-Bump@main
        with:
          method: 'regex'
          path: 'eu-gryta-ktor-utils/version.properties'
          prefix: 'v'

      - name: Push Tag
        uses: actions/github-script@v7
        if: steps.vbump.outputs.bump == 'true'
        with:
          github-token: ${{ secrets.GH_ACTIONS_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.vbump.outputs.version }}",
              sha: context.sha
            })
